export default {
    countries:[],
    states:[],
    districts:[],
    genders:[],
    qualifications:[],
    sources:[],
    enquiryStatus:[],
    followPriority:[],
    durations:[],
    followType:[],
    followReasons:[],
    references:[{ id : 1 , name : 'Malkit Singh' }, { id : 2 , name : 'Naveen Mishra' }, { id : 3 , name : 'Preeti Singh' }, { id : 4 , name : 'Varsha Yadav' },{ id : 5 , name : 'Indearpreet Singh' } ],
    counselors:[{ id : 1 , name : 'Malkit Singh' }, { id : 2 , name : 'Naveen Mishra' }, { id : 3 , name : 'Preeti Singh' }, { id : 4 , name : 'Varsha Yadav' },{ id : 5 , name : 'Indearpreet Singh' } ],
    faculties:[{ id : 1 , name : 'Preeti Singh' }, { id : 2 , name : 'Naveen Mishra' }, { id : 3 , name : 'Surjit Singh' }, { id : 4 , name : 'Varsha Yadav' },{ id : 5 , name : 'Raman Kumar' } ],
    semsters:[{ id : 1 , name : 'Sem-1' }, { id : 2 , name : 'Sem-2' }, { id : 3 , name : 'Sem-3' }, { id : 4 , name : 'Sem-4' },{ id : 5 , name : 'Sem-5' } ,{ id : 6 , name : 'Sem-6' }],
    sessions:[{ id : 1 , name : '2021-2022' }, { id : 2 , name : '2019-2020' }, { id : 3 , name : '2018-2019' }, { id : 4 , name : '2017-2016' },{ id : 5 , name : '2015-2016' } ,{ id : 6 , name : '2014-2015' }],
    repeatMonths:[{ id : 1 , name : '15 Days' , days: 15 }, { id : 2 , name : '30 Days' , days: 30 }, { id : 3 , name : '45 Days' , days: 45 }, { id : 4 , name : '60 Days' , days: 60 },{ id : 5 , name : '90 Days' , days: 90 },{ id : 6 , name : '180 Days' , days: 180 },{ id : 7 , name : '365 Days' , days: 365 },],
    batchStatus:[{ id : 1 , name : 'Active' , days: 15 }, { id : 2 , name : 'Completed' , days: 30 }, { id : 3 , name : 'Quiet' , days: 45 }],
    batchTypes:[{ id : 1 , name : 'Student' , days: 15 }, { id : 2 , name : 'Demo' , days: 30 }, { id : 3 , name : 'Employee' , days: 45 }, { id : 4 , name : 'Skill Development' , days: 60 }],
    transactionTypes:[{ id : 1 , type : 'Cash' , value: "cash" }, { id : 2 , type : 'Online' , value: "online" }, { id : 3 , type : 'Cheque' , value: "cheque" }],
    banks:[{ id : 1 , name : 'Punjab National Bank' }, { id : 2 , name : 'Bank Of Baroda' }, { id : 3 , name : 'State Bank Of India' }],
    installmentTypes:[{ id : 1 , type : 'Registration' , value: "registration" } , { id : 2 , type : 'Other' , value: "other" } ],
}