export default {
    countries:[],
    states:[],
    districts:[],
    genders:[{ id : 1 , name : 'Male' }, { id : 2 , name : 'Female' }, { id : 3 , name : 'Other' },],
    qualifications:[{ id : 1 , name : 'Metric' }, { id : 2 , name : 'Sr. Secondary' }, { id : 3 , name : 'Graduate' }, { id : 4 , name : 'Post Graduate' }, ],
    sources:[{ id : 1 , name : 'Facebook' }, { id : 2 , name : 'Just Dail' }, { id : 3 , name : 'Instagrame' }, { id : 4 , name : 'Servey' }, ],
    enquiryStatus:[{ id : 1 , name : 'Open' }, { id : 2 , name : 'In Progress' }, { id : 3 , name : 'Rejected' }, { id : 4 , name : 'Pending' },{ id : 5 , name : 'Success' } ],
    followPriority:[{ id : 1 , name : 'Cold Call' }, { id : 2 , name : 'Warm' }, { id : 3 , name : 'Hot' }, { id : 4 , name : 'Other' },{ id : 5 , name : 'Success' } ],
    followType:[{ id : 1 , name : 'Call' }, { id : 2 , name : 'Sms' }, { id : 3 , name : 'Email' }, { id : 4 , name : 'Demo' },{ id : 5 , name : 'Walk In' } ],
    references:[{ id : 1 , name : 'Malkit Singh' }, { id : 2 , name : 'Naveen Mishra' }, { id : 3 , name : 'Preeti Singh' }, { id : 4 , name : 'Varsha Yadav' },{ id : 5 , name : 'Indearpreet Singh' } ],
    counselors:[{ id : 1 , name : 'Malkit Singh' }, { id : 2 , name : 'Naveen Mishra' }, { id : 3 , name : 'Preeti Singh' }, { id : 4 , name : 'Varsha Yadav' },{ id : 5 , name : 'Indearpreet Singh' } ],
    standards:[{ id : 1 , name : 'Information Technology' }, { id : 2 , name : 'Web Designing' }, { id : 3 , name : 'Accounting' }, { id : 4 , name : 'Soft Skill' },{ id : 5 , name : 'Indearpreet Singh' } ],
    courses:[{ id : 1 , name : 'ADIT' }, { id : 2 , name : 'DOAP' }, { id : 3 , name : 'DCAD' }, { id : 4 , name : 'DCA' },{ id : 5 , name : 'DCAD' } ],
    batches:[{ id : 1 , name : 'Doap 7Am  To 8 Am' }, { id : 2 , name : 'Doap 8Am  To 9 Am' }, { id : 3 , name : 'Doap 10Am  To 12 Am' }, { id : 4 , name : 'Doap 3Am  To 4 Am' },{ id : 5 , name : 'Doap 4Am  To 5 Am' } ],
    faculties:[{ id : 1 , name : 'Preeti Singh' }, { id : 2 , name : 'Naveen Mishra' }, { id : 3 , name : 'Surjit Singh' }, { id : 4 , name : 'Varsha Yadav' },{ id : 5 , name : 'Raman Kumar' } ],
    semsters:[{ id : 1 , name : 'Sem-1' }, { id : 2 , name : 'Sem-2' }, { id : 3 , name : 'Sem-3' }, { id : 4 , name : 'Sem-4' },{ id : 5 , name : 'Sem-5' } ,{ id : 6 , name : 'Sem-6' }],
    sessions:[{ id : 1 , name : '2021-2022' }, { id : 2 , name : '2019-2020' }, { id : 3 , name : '2018-2019' }, { id : 4 , name : '2017-2016' },{ id : 5 , name : '2015-2016' } ,{ id : 6 , name : '2014-2015' }],
    durations:[{ id : 1 , name : '15 Days' , days: 15 }, { id : 2 , name : '30 Days' , days: 30 }, { id : 3 , name : '45 Days' , days: 45 }, { id : 4 , name : '60 Days' , days: 60 },{ id : 5 , name : '90 Days' , days: 90 },{ id : 6 , name : '180 Days' , days: 180 },{ id : 7 , name : '365 Days' , days: 365 },],
    repeatMonths:[{ id : 1 , name : '15 Days' , days: 15 }, { id : 2 , name : '30 Days' , days: 30 }, { id : 3 , name : '45 Days' , days: 45 }, { id : 4 , name : '60 Days' , days: 60 },{ id : 5 , name : '90 Days' , days: 90 },{ id : 6 , name : '180 Days' , days: 180 },{ id : 7 , name : '365 Days' , days: 365 },],
    batchStatus:[{ id : 1 , name : 'Active' , days: 15 }, { id : 2 , name : 'Completed' , days: 30 }, { id : 3 , name : 'Quiet' , days: 45 }],
    batchTypes:[{ id : 1 , name : 'Student' , days: 15 }, { id : 2 , name : 'Demo' , days: 30 }, { id : 3 , name : 'Employee' , days: 45 }, { id : 4 , name : 'Skill Development' , days: 60 }],
    transactionTypes:[{ id : 1 , type : 'Cash' , value: "cash" }, { id : 2 , type : 'Online' , value: "online" }, { id : 3 , type : 'Cheque' , value: "cheque" }],
    banks:[{ id : 1 , name : 'Punjab National Bank' }, { id : 2 , name : 'Bank Of Baroda' }, { id : 3 , name : 'State Bank Of India' }],
}